name: 'Copy secrets in S3'

on:
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  copySecrets:
    name: 'Copy secrets in S3'
    runs-on: ubuntu-latest
    environment: production
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_TOKEN }}

      - name: Write secrets to file
        run: |
          echo "${{secrets.EKS_AWS_AUTH_ROLES}}" >> secrets.txt
          echo "${{secrets.EKS_AWS_AUTH_USERS}}" >> secrets.txt
          echo "${{secrets.CI_CD_AUTOMATION_REPO_URL}}" >> secrets.txt

      - name: Configure AWS Credentials Action For GitHub Actions
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_GH_ACTIONS_ROLE }}
          aws-region: eu-north-1

      - name: Copy secrets
        run: |
          aws s3 cp secrets.txt s3://gh-secrets-bucket
